name: Level 2 Data (Offset 5)

on:
  schedule:
    - cron: '5/15 * * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python main.py  # Replace with your Python script's filename

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add data/*  # Add all changes within the data folder
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            TODAY_DATE=$(date +'%Y-%m-%d')
            git commit -m "Update data folder - $TODAY_DATE"
            git push origin main  # Replace with your branch name if it's not main
          fi
